language: perl6

os:
  - linux
  - osx

perl6:
  - 2016.12
  - latest

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update           ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgtk-3-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                       ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install gtk+3                ; fi

install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef build .

# Headless GUI Testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - prove -v -e "perl6 -Ilib" t/ && zef install GTK::Scintilla
